### PR TITLE
Refactory of OpenAICompatible

### PR DESCRIPTION
**Pull request by dave90**
# Description

Refactory of OpenAICompatible LLM setting.

**Key Changes:**
- refactor **CustomOpenAI** and **LLMOpenAICompatibleConfig**.  Now CustomOpenAI works with OpenAI-compatible
- removes the linkage between **CustomOpenAI** and **EmbedderOpenAICompatibleConfig** as these are no longer compatible to our LLMOpenAICompatibleConfig (due to the refactor of  CustomOpenAI) 

**Test**
Tested with openrouter.ai and ollama

Screenshot 2024-04-17 at 21 44 35
Screenshot 2024-04-17 at 21 49 04

Related to issue #759

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pieroit** [comment]
Great work, will review soon. Thanks :D
Question, how is your docker compose in order to use `host.docker.internal` ? This came up many times and would make it way easier than people trying to mess with their machine's IP

**Comment by pieroit** [comment]
@AlessandroSpallina @valentimarco could you take a look at this PR?

**Comment by dave90** [comment]
> Great work, will review soon. Thanks :D Question, how is your docker compose in order to use `host.docker.internal` ? This came up many times and would make it way easier than people trying to mess with their machine's IP

For the test with Ollama  (host.docker.internal) I added following lines in the docker-compose

```
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

This helps establish a connection with the localhost machine. I'm happy to include this configuration in the pull request if it'll make things easier :) . What do you think @pieroit ?

**Comment by pieroit** [comment]
> > Great work, will review soon. Thanks :D Question, how is your docker compose in order to use `host.docker.internal` ? This came up many times and would make it way easier than people trying to mess with their machine's IP
> 
> For the test with Ollama (host.docker.internal) I added following lines in the docker-compose
> 
> ```
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
> ```
> 
> This helps establish a connection with the localhost machine. I'm happy to include this configuration in the pull request if it'll make things easier :) . What do you think @pieroit ?

You mean as a default url for the LLM config?
We should also indicate that in the docs, I'll open an issue there

**Comment by valentimarco** [comment]
> > Great work, will review soon. Thanks :D Question, how is your docker compose in order to use `host.docker.internal` ? This came up many times and would make it way easier than people trying to mess with their machine's IP
> 
> For the test with Ollama (host.docker.internal) I added following lines in the docker-compose
> 
> ```
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
> ```
> 
> This helps establish a connection with the localhost machine. I'm happy to include this configuration in the pull request if it'll make things easier :) . What do you think @pieroit ?

this works only on linux and [must be different](https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66) for mac and win.

**Comment by valentimarco** [comment]
> @AlessandroSpallina @valentimarco could you take a look at this PR?

I will try it tomorrow

**Comment by valentimarco** [comment]
@dave90 Don't understand the pr.yml commits... ALL the tests can be executed with the following command `docker exec cheshire_cat_core python -m pytest --color=yes .`
Here the [tests docs](https://cheshire-cat-ai.github.io/docs/technical/advanced/tests/)

**Pull request merged**
