### PR TITLE
imp: speedup plugin dependencies check

### PR DESCRIPTION
**Pull request by kodaline**
# Description

Speedup plugin dependencies check

Related to issue #609 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pieroit** [comment]
@kodaline the test fails because the plugin is not activated, just call `.activate()` on it after instantiation

**Comment by kodaline** [comment]
> @kodaline the test fails because the plugin is not activated, just call `.activate()` on it after instantiation

ok, I made a PR so @Pingdred can do some tweaks, it's still in draft mode

**Comment by pieroit** [comment]
@kodaline @Pingdred I've been waiting for this with excitement!
Reviewing today ;)

**Comment by kodaline** [comment]
> @kodaline @Pingdred I've been waiting for this with excitement! Reviewing today ;)

@pieroit changing a couple of things, do not merge please

**Comment by kodaline** [comment]
> > @kodaline @Pingdred I've been waiting for this with excitement! Reviewing today ;)
> 
> @pieroit changing a couple of things, do not merge please

ok I think I am done

**Comment by pieroit** [comment]
kudos!!!

**Pull request merged**
