### PR TITLE
Updated invalid credentials message

### PR DESCRIPTION
**Pull request by josephcuenco**
# Description

-Moved error message to above the login to make it easier to see 
-Gave the message a border and background color to further catch the attention of the user and take up more space

Related to issue #927

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [O] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [O] My code follows the style guidelines of this project
- [O] I have performed a self-review of my own code
- [O] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by aaronbesc** [comment]
This PR is copying PR #929 (?)

**Comment by EKS2003** [comment]
Please check PR #929

**Comment by josephcuenco** [comment]
> This PR is copying PR #929 (?)

Wow, that was completely unintentional. I didn't even see that PR...great minds think alike I suppose.

**Comment by pieroit** [comment]
Closing as already fixed in #929
thanks anyway @josephcuenco

**Pull request closed without merging**
