### PR TITLE
Add a bash script for Linux to update repository and rebuild the images.

### PR DESCRIPTION
**Pull request by Cereal84**
The script checks if the repository is updated and if not make a git pull. The script has a '-r' option which stop the docker containers and restart them after the update.

Essentially is a bash script which perform

```bash
docker-compose down
git pull origin main
docker-compose build --no-cache
docker-compose up
```

plus some check.

### CODE REVIEW

**Comment by pieroit** [comment]
Thanks
Leaving this PR open as we decide if creating a full blown CLI or a `scripts` folder

**Comment by Cereal84** [comment]
> Thanks
> Leaving this PR open as we decide if creating a full blown CLI or a `scripts` folder

In my opinion having a CLI tool is better than a set of scripts.

**Comment by pieroit** [comment]
Still interested in working on the CLI?
There is a proposal from @EugenioPetulla [here](https://github.com/EugenioPetulla/CLI-Cheshire-Cat-Chat)

**Comment by pieroit** [comment]
Closing this issue, ok CLI but bash is linux only... let's go with Python

**Pull request closed without merging**
