### PR TITLE
Added anthropic as supported llm provider

### PR DESCRIPTION
**Pull request by lucagobbi**
# Description

This PR to add Anthropic as LLM provider. Since we support OpenAI, Cohere and Gemini I thought it was a little bit racist to exclude Anthropic outright. 

I removed an old dependency `anthropic==0.2.9`, honestly idk what purpose it served since Anthropic wasn't supported.
As mentioned in #952, we may need a langchain update, that's why I was forced to use `langchain-anthropic==0.1.23` even if the latest is `0.2.4`, time to make some updates.

Anthropic doesn't offer its own embedding models as they say [here](https://docs.anthropic.com/en/docs/build-with-claude/embeddings#how-to-get-embeddings-with-anthropic), they have a strong relationship with Voyage AI, should we support them among the other embedders? 

Related to issue #961 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by valentimarco** [comment]
> Anthropic doesn't offer its own embedding models as they say [here](https://docs.anthropic.com/en/docs/build-with-claude/embeddings#how-to-get-embeddings-with-anthropic), they have a strong relationship with Voyage AI, should we support them among the other embedders?

Yes but do not put as automatic embedder when selecting the model. We should remove that feature...
If you add this and fix the linting, i can merge it

**Comment by pieroit** [comment]
Thanks @lucagobbi awesome
Agree time to update langchain, but last time I tried I **cried**

@valentimarco is right we'll take away the automatic sync between LLM and embedders*, so just Anthropic LLM is just fine.

Need to refactor vector memory a little so when one switches embedders collections are not deleted; once that is done embedder setting is not automatic, user gets notifified via chat in the same way he/she is notified about the LLM

**Comment by lucagobbi** [comment]
@pieroit I'd like to use Voyage AI for some stuff, as I understand correctly you wouldnt add it as supported by default, is it correct? If yes, I'll create a plugin for that. If not, I can add the default factory. Thankss

**Comment by pieroit** [comment]
> @pieroit I'd like to use Voyage AI for some stuff, as I understand correctly you wouldnt add it as supported by default, is it correct? If yes, I'll create a plugin for that. If not, I can add the default factory. Thankss

Yep go for a plugin please
Let's keep as "core included" only the top names (open and closed)

**Pull request merged**
