### PR TITLE
Pre-built Docker image

### PR DESCRIPTION
**Pull request by nicola-corbellini**
# Description

This PR updates the workflow to build and push a built docker image of the core.
You can keep this open and use it as a reference when we're ready to do this step.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by nicola-corbellini** [comment]
If you plan to merge this, please remember to squash the commits.

**Comment by pieroit** [comment]
Thanks we'll review together if you are available

**Comment by nicola-corbellini** [comment]
Sure

**Comment by pieroit** [comment]
You da best

**Pull request merged**
