### PR TITLE
Support for GitHub Codespaces

### PR DESCRIPTION
**Pull request by zioproto**
# Description

Makes possible to run the Cat in GitHub Codespaces.

### CODE REVIEW

**Comment by zioproto** [comment]
You can test following this link:
https://github.com/codespaces/new?hide_repo_select=true&ref=codespaces&repo=629450469&skip_quickstart=true&machine=standardLinux32gb&devcontainer_path=.devcontainer%2Fdevcontainer.json&geo=EuropeWest

**Comment by pieroit** [comment]
The codespace opened under my account, I run docker-compose up but then still 404

**Comment by pieroit** [comment]
Also I see there is a billing system for codespaces, is the org going to pay to host cat instances?

**Comment by zioproto** [comment]
> Also I see there is a billing system for codespaces, is the org going to pay to host cat instances?

https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces#how-billing-is-handled-for-forked-repositories
Usage of codespaces created from a forked repository will be billed to your personal account unless the upstream (or parent) repository is in an organization that has allowed you - as a member, or outside collaborator, of the organization - to use codespaces at the organization's expense.

**Pull request merged**
