### PR TITLE
Scheduler update

### PR DESCRIPTION
**Pull request by jacopopalumbo01**
# Description

Now the StrayCat has the WhiteRabbit property. Added the `schedule_jobs`. There are some missing things (like the other types of scheduling discussed in #839.

With this update you can schedule a job like follows:
```python
def job(cat):
    cat.send_ws_message(content="White Rabbit: Oh dear! Oh dear! I shall be too late!", msg_type="chat")
    
@hook
def before_cat_sends_message(final_output, cat):    
    cat.white_rabbit.schedule_job(job, seconds=10, cat=cat)
    return final_output
```

Notice: If you don't need the cat instance in the scheduled job you can just ignore it, now it is handled as a kwarg. This means that you can also pass other attributes to the method. Example:
```python
def job(log_message):
    log.debug(log_message)
    
@hook
def before_cat_sends_message(final_output, cat):    
    cat.white_rabbit.schedule_job(job, seconds=10, log_message="Hello world")
    return final_output
```

Related to PR #836 discussion and #839 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pieroit** [comment]
Looks good to me!

The StrayCat instance passing is now present both in RabbitHole and WhiteRabbite, at one point we could figure out a way to implicitly pass it, whenever the methods are called from a Stray instance. I'll propose for Cat v2, because it requires architectural changes :D

image

**Comment by jacopopalumbo01** [comment]
Update:
- Added a `listener` to the scheduler. Now there is a log about the scheduled job behavior after job ends.
- Added `schedule_interval_job()` to schedule recurrent jobs

Next thing to do: implement `cron` type.

Another interesting idea could be a decorator for jobs that do not start inside a hook or a tool.
It should be something like that:
```python
@schedule(date=date)
def func():
     log.info("WhiteRabbit: Hi there!")
```
What do you think?

P.S.
APScheduler job can also accept an id or a name as parameter. Do you think that we should add those arguments? I'm thinking about managing jobs. We can provide a method to get the scheduled jobs and one to delete them. By having custom ids and names it could be more accessible.

**Comment by lucagobbi** [comment]
Really like this! About the `@schedule` annotation I'm quite neutral, one could instantiate the CheshireCat or directly the WhiteRabbit in his/here plugin code, since they are singleton and schedule the function directly there. But, if it is a requested feature it's for sure less verbose with the annotation.

About the id/name of the scheduled jobs I totally agree: if you start a recurrent task at the moment you cannot delete it at runtime (maybe inserting some logic in the scheduled job itself, but sometimes may not be such a cool idea). Plus, in the future, one could build a plugin(the  _WhiteRabbitInAction_) that creates job, deletes them, pauses them, etc.

**Comment by jacopopalumbo01** [comment]
Update: Added ids management, `get_jobs`, `remove_job`, `schedule_cron_job` methods.

**Comment by pieroit** [comment]
> Update:
> 
> * Added a `listener` to the scheduler. Now there is a log about the scheduled job behavior after job ends.
> * Added `schedule_interval_job()` to schedule recurrent jobs
> 
> Next thing to do: implement `cron` type.
> 
> Another interesting idea could be a decorator for jobs that do not start inside a hook or a tool. It should be something like that:
> 
> ```python
> @schedule(date=date)
> def func():
>      log.info("WhiteRabbit: Hi there!")
> ```
> 
> What do you think?
> 
> P.S. APScheduler job can also accept an id or a name as parameter. Do you think that we should add those arguments? I'm thinking about managing jobs. We can provide a method to get the scheduled jobs and one to delete them. By having custom ids and names it could be more accessible.

Awesome!
Let's wait for a dedicated decorator, after there is some usage for this utility we can better understand what is needed

Thanks @jacopopalumbo01 @lucagobbi

**Pull request merged**
