### PR TITLE
Embedders and LLMs with different vendors

### PR DESCRIPTION
**Pull request by sirius-0**
# Description

Enabled the use of Embedders and LLMs that have different vendors.

Related to issue #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by sirius-0** [comment]
I didn't want to close it, it was a mistake

**Comment by pieroit** [comment]
Thanks, merging today

**Comment by pieroit** [comment]
@sirius-0 thanks a lot also for refactoring the `upsert_setting`, much appreciated :D

@nickprock from now on LLM and embedder are totally independent.
When the cat starts, it only chooses same-vendor embedder if there is no db config about the embedder.
See [here](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/mad_hatter/core_plugin/hooks/models.py#L89)

**Comment by nickprock** [comment]
Great! I'm going to test tomorrow the new features!

**Pull request merged**
