### PR TITLE
Added support for other mimetypes in plugin upload

### PR DESCRIPTION
**Pull request by zAlweNy26**
# Description

I added support for .tar files when uploading files via endpoint `/plugins/upload`. 
In this way it is also extendable in the future in case of support for other formats.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by zAlweNy26** [comment]
Oops I didn't saw #345 , I apologize. @pieroit tell me if I should close this one.

**Comment by pieroit** [comment]
@zAlweNy26 thanks, I'll merge this one first and then ask the other PR contributor to align some of the code to what we will do in the Mad Hatter

**Comment by pieroit** [comment]
@zAlweNy26 I suggest in the future you make a specific branch for a PR, as all other contributors do.
It is a good practice because:
- you can pull new code on main while the PR is not yet merged
- every PR you do is on a different branch and so no confusion is made with main
Thanks

**Comment by zAlweNy26** [comment]
Thanks for the suggestion, I will do it next time

**Pull request merged**
