### PR TITLE
Add endpoint to message with Cat

### PR DESCRIPTION
**Pull request by zAlweNy26**
# Description

I also:
- fixed some typos around the codebase
- replaced old logic for user id

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pieroit** [comment]
Thanks there are good ideas in the PR

Questions:
- why the `save` param? Looks a lot like the prompt settings we ended up taking away, and nobody asked for it
- what happens to tokens streaming and notifications when a client uses `POST /message`?

I agree on http endpoints, but what do we say to devs? Use http without streaming or use websocket for streaming?

What do you think @nicola-corbellini @Pingdred @valentimarco

**Comment by zAlweNy26** [comment]
Hi @pieroit, thanks for the response.
- The `save` param is just a boolean param to decide whether or not to save the response in the chat history.
- Everything works fine, no notifications (because it's not a file upload) and no tokens streaming.

I don't know if HTTP streaming can be implemented, but I can check.
About the devs, just tell them that they have another way to message the cat, it's logical that an HTTP endpoint doesn't have streaming by default.

**Comment by valentimarco** [comment]
> Thanks there are good ideas in the PR
> 
> Questions:
> 
>     * why the `save` param? Looks a lot like the prompt settings we ended up taking away, and nobody asked for it
> 
>     * what happens to tokens streaming and notifications when a client uses `POST /message`?
> 
> 
> I agree on http endpoints, but what do we say to devs? Use http without streaming and use websocket for streaming?
> 
> What do you think @nicola-corbellini @Pingdred @valentimarco

Save messages is a pretty good feature and can be good when for example we don't want the tool response (with redirect on true) in the chat history!

We should find a way to generate the messages via http like most of runners do..

**Comment by nicola-corbellini** [comment]
I don't understand how one could pass `save=True` or `False`. I mean, since it is in the `__call__` method, I have no use cases in mind where one uses `stray_cat(message, save=True/False)`

**Comment by zAlweNy26** [comment]
@nicola-corbellini I didn't mean "internal" use cases, but probably from the outside someone could want to get a cat response without saving the answer to chat history. Some use cases could be: privacy, testing, resources management.

**Comment by zAlweNy26** [comment]
This makes even more sense if we finally decide to save chat history into the db

**Comment by nicola-corbellini** [comment]
Exactly, I don't understand in which case, from the outside, one calls directly the instance like this `stray_cat()`

**Comment by zAlweNy26** [comment]
Then I don't understand your doubt. What else should be called?

**Comment by nicola-corbellini** [comment]
write a snippet in which you use the parameter please

**Comment by zAlweNy26** [comment]
```js
fetch('/message?save=false', {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    text: "hello cat!"
  }),
})
```

**Comment by nicola-corbellini** [comment]
Ah lol now I get it, I didn't see it was a param in the new endpoint

**Comment by zAlweNy26** [comment]
Buy a new pair of glasses

**Comment by nicola-corbellini** [comment]
make two separate PRs for typos and new logic 😛

**Comment by zAlweNy26** [comment]
No I won't

**Pull request merged**
