### PR TITLE
Fix huggingface endpoint integration

### PR DESCRIPTION
**Pull request by valentimarco**
# Description

Fixed Huggingface endpoint integration.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by nicola-corbellini** [comment]
@valentimarco something wrong in the commit history and the Dockerfile's got edited

**Comment by valentimarco** [comment]
Uhm....but i did the update of the fork...

**Comment by nicola-corbellini** [comment]
btw you sure adding the streaming parameter is enough to fix the bug? Have you tested it with a HF endpoint?

**Comment by valentimarco** [comment]
> btw you sure removing the streaming parameter is enough to fix the bug? Have you tested it with a HF endpoint?

Eh eh... I dont have the api Key ;(

**Comment by pieroit** [comment]
This PR is messed up, I guess you merged after branching and there is stuff from main
 let's retry ;)

**Pull request closed without merging**
