### PR TITLE
Fix Exception handling in case an incorrect key is loaded.

### PR DESCRIPTION
**Pull request by ethanlacerenza**
# Fix Exception handling in case an incorrect key is loaded.

This fix prevents the application from crashing when an incorrect API key is entered. If an incorrect key is detected, it removes the erroneous key, provides an error message, and restores the default LLM.

### **Invalid Key:** Sorry for the slow gif, but it's due to compression

> Registrazione schermo 2023-11-17 alle 13 17 23

###  **Exceeded quota:**

> ezgif com-gif-maker

### **In case it's a valid key**

> Registrazione-schermo-2023-11-17-alle-15 45 47

### **logs (no exception) - No crash**

> image

Related to issue #572

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by ethanlacerenza** [comment]
I noticed another issue, and I'm trying to fix that as well before closing it. I'll update you as soon as possible.

**Comment by pieroit** [comment]
Thanks will review soon :)

**Comment by pieroit** [comment]
Thanks will review soon :)

**Comment by pieroit** [comment]
Thanks and welcome on board @ethanlacerenza !

**Pull request merged**
