### PR TITLE
Updated hook decorator

### PR DESCRIPTION
**Pull request by zAlweNy26**
# Description

In this way, a plugin developer can either define the hook using the function name or using the `name` argument of the @hook with the help of the autocomplete thanks to the Literal `CAT_HOOKS`.

Thanks to this PR, we still support the old way of defining hooks, but also adding a new and easier way to define them.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by zAlweNy26** [comment]
@pieroit @nicola-corbellini what do you think about this?

**Comment by pieroit** [comment]
> @pieroit @nicola-corbellini what do you think about this?

I'll leave the PR open, but I'm not convinced it is worth it to have this just for autocomplete

**Comment by zAlweNy26** [comment]
But nothing breaks, everything continues to work as before, there is simply this new extra mode for those who want to 😁

**Comment by nicola-corbellini** [comment]
apart from merging this or not, I'd populate the `Literal` list programmatically rather than hard coding the hooks' names

**Comment by zAlweNy26** [comment]
How can it be done?

**Pull request closed without merging**
