### PR TITLE
Feature/delete points by source

### PR DESCRIPTION
**Pull request by AlboCode**
# Description

Add an endpoint to delete points based on source, which potentially can be expanded to filter delete by all the metadata properties.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by zAlweNy26** [comment]
Looks good, but please update the description 😊

**Comment by AlboCode** [comment]
@zAlweNy26 Done

**Comment by giovannialbero1992** [comment]
Hi all, any chance to see this PR merged? :-)

**Comment by giovannialbero1992** [comment]
great to hear that! 😄

**Comment by pieroit** [comment]
Also, there should be a test for this (under `tests/routes/memory/`

**Comment by pieroit** [comment]
@AlboCode merged your commits into `develop` thanks

@AlboCode @giovannialbero1992 I made the endpoint more general for other metadata

```python
metadata = {
    "source": "sample.pdf"
}
client.request("DELETE", "/memory/collections/declarative/points", json=metadata)
```

Also check the tests about the endpoint [here](https://github.com/cheshire-cat-ai/core/blob/010fa62a36763c77d3ee0dd1be9adeabc3aa68e5/core/tests/routes/memory/test_memory_points.py#L54)

This can do for the moment, problems:
- `DELETE` verb should not support a JSON
- the whole CRUD and filtering about points should be designed top down, in order to make it flexible enough for many use cases (if you would like to make a proposal, you are welcome - let's draft the endpoints in an issue)

Thanks

**Comment by giovannialbero1992** [comment]
Thanks @pieroit

**Pull request merged**
