### PR TITLE
Non-Root User Configuration to Dockerfile

### PR DESCRIPTION
**Pull request by dave90**
# Description

Updates Dockerfile to improve container security by introducing non-root user configurations.

- Parameterization of User and Group IDs: build-time arguments (USER_ONBUILD, UID_ONBUILD, GROUP_ONBUILD, GID_ONBUILD) to dynamically set the user ID (UID) and group ID (GID) along with the corresponding user and group names.
- User and Group Creation: creation of a non-root user (USER_ONBUILD) and group (GROUP_ONBUILD) with the specified UID and GID 
- Directory Ownership: The ownership of the /app directory is changed to the newly created non-root user and group

Related to issue #765

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by dave90** [comment]
installation of plugin dependencies occurs before the switch to a non-root user, eliminating any potential issues. Following the snippet:

```
...
RUN python3 install_plugin_dependencies.py

### ADD USER ###
RUN groupadd -g ${GID_ONBUILD} ${GROUP_ONBUILD} && \
   useradd -m -u ${UID_ONBUILD} -g ${GROUP_ONBUILD} ${USER_ONBUILD} \
   && chown -R ${GROUP_ONBUILD}:${USER_ONBUILD} /app

USER ${GROUP_ONBUILD}:${UID_ONBUILD}
...
```

**Comment by pieroit** [comment]
> installation of plugin dependencies occurs before the switch to a non-root user, eliminating any potential issues. Following the snippet:
> 
> ```
> ...
> RUN python3 install_plugin_dependencies.py
> 
> ### ADD USER ###
> RUN groupadd -g ${GID_ONBUILD} ${GROUP_ONBUILD} && \
>    useradd -m -u ${UID_ONBUILD} -g ${GROUP_ONBUILD} ${USER_ONBUILD} \
>    && chown -R ${GROUP_ONBUILD}:${USER_ONBUILD} /app
> 
> USER ${GROUP_ONBUILD}:${USER_ONBUILD}
> ...
> ```

Plugins can also be installed and activated after the image has been built:
https://github.com/cheshire-cat-ai/core/blob/4c9fff02470ecd406a346652d035aa98ada71d58/core/cat/mad_hatter/plugin.py#L68

That makes things more complicated :(
P.S.: thanks for reasoning over this issue

**Comment by dave90** [comment]
Good point :). Therefore, I've updated the Dockerfile to include a local bin directory in the user's PATH. This modification enables the installation of python packages in a local directory allowing users to install new packages at runtime.

**Comment by pieroit** [comment]
> Good point :). Therefore, I've updated the Dockerfile to include a local bin directory in the user's PATH. This modification enables the installation of python packages in a local directory allowing users to install new packages at runtime.

Thanks I'm going to try this out

**Comment by dave90** [comment]
Closed this pull request and created a new one: -> #790

**Pull request closed without merging**
