### PR TITLE
imp: ad hoc method for max user input

### PR DESCRIPTION
**Pull request by kodaline**
## Description

Added ad hoc method to manage very long input messages

Improvement for issue #588 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by kodaline** [comment]
@pieroit do not merge this yet, I want to make some changes

**Comment by pieroit** [comment]
> @pieroit do not merge this yet, I want to make some changes

Ok!

**Comment by Pingdred** [comment]
I don't know if I understand correctly, but this way if the user's question is too long it will be sent down the rabbit hole but the agent will continue to work as usual, what is the reason for doing this?

**Comment by kodaline** [comment]
> I don't know if I understand correctly, but this way if the user's question is too long it will be sent down the rabbit hole but the agent will continue to work as usual, what is the reason for doing this?

this was done to avoid crashes in case of sending too long messages, that makes openai crash for example, because the model accepts less tokens

**Comment by pieroit** [comment]
@Pingdred @kodaline let's merge it, and later on design a way to jump directly to final response without involving nor the agent, nor recall. May be useful for a reflex-like response in a lot of situations, also for plugins

**Comment by Pingdred** [comment]
Yes, I remember the problem, but from what I have seen the user message is not changed, so the agent input is still the same, am I missing something?

**Comment by kodaline** [comment]
> @Pingdred @kodaline let's merge it, and later on design a way to jump directly to final response without involving nor the agent, nor recall. May be useful for a reflex-like response in a lot of situations, also for plugins

I can rework this one, as you prefer

**Comment by kodaline** [comment]
> Yes, I remember the problem, but from what I have seen the user message is not changed, so the agent input is still the same, am I missing something?

I know, I noticed that too, but initially the idea was to do it as it is now, actually I wanted to talk to Piero about this XD

**Comment by pieroit** [comment]
@kodaline yes it is perfect! Thanks

**Comment by kodaline** [comment]
> @kodaline yes it is perfect! Thanks

ok, will rework this one directly, I think it's the best thing to do
would you briefly explain the new behaviour?

**Comment by pieroit** [comment]
@kodaline sorry I'll explain myself better

Since the "reflex" must be designed and should offer a new hook, I prefer this PR as is and later on have a talk

**Comment by pieroit** [comment]
Thanks @kodaline :dagger:
@Pingdred I got only now what you meant, fixed [here](https://github.com/cheshire-cat-ai/core/blob/000eeba3b8e456e838ab5f98f44be8a99d8824b3/core/cat/looking_glass/stray_cat.py#L333)

When you are free, we can design the mitical `reflex` hook

**Pull request merged**
