### PR TITLE
Added allowed mime-types endpoint

### PR DESCRIPTION
**Pull request by zAlweNy26**
# Description

As discussed with the core contributors, we decided to add an endpoint to give the frontend the possibility to know in advance the allowed mime-types for a better UX.

I don't understand why `ccat.rabbit_hole.file_handlers.keys()` throws an error, so I did it in another way.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pieroit** [comment]
@zAlweNy26 I guess it has to be converted to list:

```python
admitted_types = list(ccat.rabbit_hole.file_handlers.keys())
```

**Comment by pieroit** [comment]
> Which way do you prefer?

`list(x)`, of course :heart:

**Comment by zAlweNy26** [comment]
Fixed :)

**Comment by pieroit** [comment]
Thanks!

**Pull request merged**
