### PR TITLE
Add New POST Endpoint /memory/recall

### PR DESCRIPTION
**Pull request by dave90**
# Description

This PR create a new POST endpoint _/memory/recall_ that accept a json with this format:
```
{
    "text": "...",
    "k": 34,
    "metadata": {}
}
```

metadata is a simple flat dictionary to search in AND

Endpoint GET /memory/recall remain and log a warning that is going to be deprecated in the next major version.

Related to issue #899 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by matteocacciola** [comment]
A POST request to get info from the vector database?🤔

**Comment by lucagobbi** [comment]
> A POST request to get info from the vector database?🤔

How would you filter by metadata using a GET request? Seems to be a pretty common practice: [Qdrant](https://api.qdrant.tech/api-reference/points/get-points), [Pinecone](https://docs.pinecone.io/reference/api/2024-10/data-plane/query)

**Comment by pieroit** [comment]
Thanks @dave90 !!
Didn't know there was a `deprecated` flag in fastAPI

**Comment by matteocacciola** [comment]
I had the time to try something. Here is how the code could have been changed
```
@router.get("/recall")
async def recall_memory_points_from_text(
    request: Request,
    text: str = Query(description="Find memories similar to this text."),
    k: int = Query(default=100, description="How many memories to return."),
    metadata: Dict[str, Any] = Depends(create_dict_parser(
        "metadata",
        description="Flat dictionary where each key-value pair represents a filter."
                    "The memory points returned will match the specified metadata criteria."
    )),
    stray: StrayCat = Depends(HTTPAuth(AuthResource.MEMORY, AuthPermission.READ)),
) -> Dict:
...
```

and here is the 'create_dict_parser`
```
def create_dict_parser(param_name: str, description: str | None = None):
    def parser(
        param_value: str | None = Query(
            default=None,
            alias=param_name,
            description=description or f"{param_name} JSON filter."
        )
    ) -> Dict[str, Any]:
        if param_value is None or not param_value:
            return {}
        try:
            return json.loads(param_value.replace("'", "\""))
        except json.JSONDecodeError:
            return {}
    return parser
```

and no changes to the new test, except the `get` rather than the `post` request :-).

**Pull request merged**
